Repository getsentry/sentry-go, pull requests merged in 2022-11, with the labels that each got.

#460 Make maximum amount of spans configurable
  CHANGELOG.md
  client.go
  client_test.go
  span_recorder.go
  span_recorder_test.go
Labels: Type: Improvement, Status: Confirmed

#485 feat: Add ClientOptions.SendDefaultPii
  CHANGELOG.md
  client.go
  fasthttp/sentryfasthttp_test.go
  http/sentryhttp_test.go
  interfaces.go
  interfaces_test.go
Labels: Status: In Progress, Type: Feature

#490 ref: Rename ClientOptions.SendDefaultPii to ClientOptions.SendDefaultPII
  CHANGELOG.md
  client.go
  fasthttp/sentryfasthttp_test.go
  http/sentryhttp_test.go
  interfaces.go
  interfaces_test.go
Labels: Type: Improvement, Status: Confirmed

#495 docs: Update changelog
  CHANGELOG.md
Labels: Type: Documentation

#471 Add logrus support
  example/logrus/main.go
  go.mod
  logrus/logrusentry.go
  logrus/logrusentry_test.go
Labels: Status: In Progress, Type: Feature

#498 ref: Unify TracesSampler
  CHANGELOG.md
  client.go
  example/http/main.go
  internal/crypto/randutil/randutil.go
  internal/crypto/randutil/randutil_test.go
  traces_sampler.go
  traces_sampler_test.go
  tracing.go
  tracing_test.go
Labels: Status: In Progress, Type: Breaking, Type: Refactoring

#492 [Dynamic Sampling] Head of trace
  dynamic_sampling_context.go
  dynamic_sampling_context_test.go
  http/sentryhttp.go
  interfaces.go
  tracing.go
Labels: Status: In Progress, Type: Feature
