Repository getsentry/sentry-go, pull requests merged in 2022-10, with the labels that each got.

#483 feat: Extend User struct by adding Data, Name and Segment
  CHANGELOG.md
  interfaces.go
  interfaces_test.go
  scope.go
  scope_test.go
Labels: Type: Feature, Status: Confirmed

#487 docs: Run go fmt
  doc.go
  dsn_test.go
  stacktrace_external_test.go
  stacktrace_test.go
  tracing.go
  util.go
Labels: Type: Documentation, Status: Confirmed

#446 fix: Scope values should not override Event values
  scope.go
  scope_test.go
Labels: Status: Confirmed, Type: Bug
