Repository getsentry/sentry-go, pull requests merged in 2023-04, with the labels that each got.

#618 ci: Do not test with GOPATH mode anymore
  .github/workflows/test.yml
Labels: Status: In Progress

#617 fix(ci): Increase timeout for golangci-lint
  .github/workflows/lint.yml
Labels: Status: In Progress, Type: Improvement

#621 fix: Update _examples/http
  _examples/http/main.go
Labels: Status: Confirmed, Type: Bug

#623 doc: Link to the repository and official docs in doc.go
  doc.go
Labels: Status: In Progress, Type: Documentation

#608 feat: Add Event.SetException
  client.go
  interfaces.go
Labels: Status: In Progress, Type: Feature
