Repository getsentry/sentry-go, pull requests merged in 2023-10, with the labels that each got.

#727 Remove deprecated code
  sentry.go
Labels: Type: Breaking, Type: Improvement

#728 Prepare 0.25.0
  CHANGELOG.md
Labels: Type: Documentation

#729 Update changelog to mention Breaking Changes
  CHANGELOG.md
Labels: Type: Documentation

#737 fix(util): check if git command exists when setting release
  util.go
Labels: Type: Improvement
