Repository getsentry/sentry-go, pull requests merged in 2023-02, with the labels that each got.

#559 fix(otel): Fix Dynamic Sampling context propagation for nested spans
  helpers_test.go
  otel/helpers_test.go
  otel/propagator.go
  otel/propagator_test.go
  tracing.go
  tracing_test.go
Labels: Type: Improvement, Topic: OpenTelemetry

#562 ref(test): Move assert* helpers to internal package
  helpers_test.go
  internal/testutils/asserts.go
  otel/helpers_test.go
  otel/span_processor_test.go
Labels: Status: In Progress, Type: Refactoring

#565 release: Update .craft.yml to be ready for otel submodule release
  .craft.yml
Labels: Status: In Progress, Type: Feature

#566 fix: Create a frozen DSC when calling ToBaggage
  dynamic_sampling_context_test.go
  otel/propagator.go
  otel/span_processor_test.go
  tracing.go
  tracing_test.go
Labels: Status: In Progress, Type: Bug

#567 fix(otel): Reduce minimal required OTel SDK version to 1.11.0
  otel/go.mod
  otel/go.sum
Labels: Status: In Progress, Topic: OpenTelemetry

#569 test: Add Codecov configuration file
  .codecov.yml
Labels: Type: Improvement

#568 fix(baggage): Update baggage parsing and encoding in vendored otel package
  go.mod
  internal/otel/baggage/README.md
  internal/otel/baggage/baggage.go
  internal/otel/baggage/baggage_test.go
Labels: Status: In Progress

#573 fix(otel): Use vendored bagggage implementation in propagator
  otel/context.go
  otel/helpers_test.go
  otel/propagator.go
  otel/propagator_test.go
Labels: Status: In Progress

#572 doc: Prepare 0.18.0
  CHANGELOG.md
Labels: Type: Documentation

#577 fix(ci): Run "build", "vet", and "mod tidy" for all submodules
  .github/workflows/test.yml
  Makefile
Labels: Type: Improvement

#564 feat: add support for exception mechanism metadata
  interfaces.go
  interfaces_test.go
Labels: Status: In Progress, Type: Feature

#583 Switch to MIT license
  LICENSE
Labels: Type: Documentation

#580 fix(otel): Overwrite "trace" context in Sentry error
  otel/event_processor.go
  otel/event_processor_test.go
Labels: Status: In Progress, Topic: OpenTelemetry

#563 ci: Add Go 1.20 and remove Go 1.17
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Makefile
  go.mod
  otel/go.mod
  otel/internal/dummy/dummy.go
Labels: Status: In Progress, Type: Improvement

#589 doc: Prepare 0.19.0 release
  CHANGELOG.md
Labels: Status: In Progress

#590 doc: Mention golang.org/x/text version bump in CHANGELOG
  CHANGELOG.md
Labels: Status: In Progress
