Repository getsentry/sentry-go, pull requests merged in 2023-03, with the labels that each got.

#597 Steven is a Go contributor
  otel/span_processor.go
Labels: Type: Documentation

#603 ref: Align SetContext
  tracing.go
Labels: Type: Improvement

#610 fix(otel): Better handling for HTTP span attributes
  otel/internal/utils/spanattributes.go
  otel/span_processor_test.go
Labels: Status: In Progress, Topic: OpenTelemetry

#615 fix(build): Temporarily remove otel module when building in GOPATH mode
  .github/workflows/test.yml
Labels: Status: In Progress, Topic: OpenTelemetry

#614 doc: Update attributions for vendored "baggage"
  internal/otel/baggage/baggage.go
  internal/otel/baggage/baggage_test.go
  internal/otel/baggage/internal/baggage/baggage.go
Labels: Status: In Progress, Type: Documentation
