Repository getsentry/sentry-go, pull requests merged in 2023-08, with the labels that each got.

#682 fix(tests): Bump timeout to 15 minutes, update cache behavior
  .github/workflows/test.yml
Labels: Status: In Progress

#684 fix: OTel incorrect usage of attributes.Value.AsString resulting in an empty string for non-string values
  otel/internal/utils/mapotelstatus.go
  otel/internal/utils/mapotelstatus_test.go
  otel/span_processor.go
Labels: Type: Bug

#695 ci: add go1.21
  .github/workflows/lint.yml
  .github/workflows/test.yml
  CHANGELOG.md
  internal/traceparser/parser.go
  internal/traceparser/parser_test.go
  profiler_test.go
Labels: Type: Improvement

#696 ci: update actions
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: Type: Improvement

#702 test: deduplicate Flush() timeout settings
  fasthttp/sentryfasthttp_test.go
  gin/sentrygin_test.go
  http/sentryhttp_test.go
  internal/testutils/consts.go
  logrus/logrusentry_test.go
  profiler_test.go
  transport_test.go
Labels: Type: Improvement

#655 Single profiler goroutine
  CHANGELOG.md
  profile_sample.go
  profiler.go
  profiler_test.go
  profiler_windows.go
  traces_profiler.go
  traces_profiler_test.go
  tracing.go
  transport_test.go
Labels: Status: In Progress, Type: Improvement

#694 Set SDK Name According Framework being used
  client.go
  client_test.go
  dsn.go
  echo/sentryecho.go
  fasthttp/sentryfasthttp.go
  gin/sentrygin.go
  http/sentryhttp.go
  iris/sentryiris.go
  logrus/logrusentry.go
  martini/sentrymartini.go
  negroni/sentrynegroni.go
  sentry.go
  transport.go
  transport_test.go
Labels: Type: Improvement
