Repository getsentry/sentry-go, pull requests merged in 2023-07, with the labels that each got.

#663 fix: Increase flush timeout in TestHTTPTransport
  transport_test.go
Labels: Status: In Progress, Type: Bug

#660 fix(tracing): Make Span.Finish a no-op when the span is already finished
  tracing.go
  tracing_test.go
Labels: Status: In Progress, Type: Bug

#666 feat(tracing): Add the sampling decision to the trace envelope header
  dynamic_sampling_context.go
  dynamic_sampling_context_test.go
  otel/propagator_test.go
  otel/span_processor_test.go
  tracing_test.go
Labels: Status: In Progress, Type: Improvement

#661 feat(crons): initial cron support
  check_in.go
  client.go
  client_test.go
  hub.go
  hub_test.go
  interfaces.go
  marshal_test.go
  sentry.go
  testdata/json/checkin/000.json
  testdata/json/checkin/001.json
  testdata/json/checkin/002.json
Labels: Status: In Progress, Type: Feature

#670 feat: Attachments support
  client_test.go
  fasthttp/sentryfasthttp_test.go
  gin/sentrygin_test.go
  http/sentryhttp_test.go
  interfaces.go
  logrus/logrusentry_test.go
  scope.go
  scope_concurrency_test.go
  scope_test.go
  tracing_test.go
  transport.go
  transport_test.go
Labels: Status: In Progress, Type: Feature

#672 Expose SpanFromContext
  tracing.go
  tracing_test.go
Labels: Status: In Progress, Type: Improvement
