Repository getsentry/sentry-go, pull requests merged in 2023-09, with the labels that each got.

#704 feat: Read release info from build info
  util.go
  util_test.go
Labels: Status: In Progress

#715 fix: Guard against a nil client when setting the SDK identifer
  echo/sentryecho.go
  fasthttp/sentryfasthttp.go
  gin/sentrygin.go
  http/sentryhttp.go
  iris/sentryiris.go
  martini/sentrymartini.go
  negroni/sentrynegroni.go
Labels: Type: Bug

#716 Prepare 0.24.1
  CHANGELOG.md
Labels: Type: Documentation

#717 feat: support IgnoreTransactions client option
  client.go
  client_test.go
  integrations.go
  integrations_test.go
Labels: Status: In Progress, Type: Feature

#718 feat: global tags
  client.go
  integrations.go
  integrations_test.go
Labels: Status: In Progress, Type: Feature

#720 Clarify the usage of `dsn.RequestHeaders()`
  dsn.go
Labels: Type: Improvement

#721 Add the SDK version when functions will be removed to `Deprecated:` c…
  tracing.go
Labels: Type: Documentation
