Repository getsentry/sentry-go, pull requests merged in 2023-01, with the labels that each got.

#519 fix: Use "example.com" host in example/test DSNs
  client_test.go
  example/feature-showcase/main.go
  example/flush/main.go
  example/multiclient/main.go
  example/recover/main.go
  example/synctransport/main.go
  example/with_extra/main.go
  hub_test.go
Labels: Type: Improvement

#521 ref: Rename example/ directory to _examples/
  .github/workflows/test.yml
  CHANGELOG.md
  _examples/basic/main.go
  _examples/echo/main.go
  _examples/fasthttp/main.go
  _examples/feature-showcase/main.go
  _examples/flush/main.go
  _examples/gin/main.go
  _examples/http/main.go
  _examples/iris/main.go
  _examples/logrus/main.go
  _examples/martini/main.go
  _examples/multiclient/main.go
  _examples/negroni/main.go
  _examples/recover-repanic/main.go
  _examples/recover/main.go
  _examples/synctransport/main.go
  _examples/with_extra/main.go
  doc.go
  echo/README.md
  fasthttp/README.md
  gin/README.md
  go.mod
  go.sum
  http/README.md
  http/example_test.go
  iris/README.md
  martini/README.md
  negroni/README.md
Labels: Type: Improvement

#517 feat: Add BeforeSendTransaction hook
  CHANGELOG.md
  _examples/http/main.go
  client.go
  client_test.go
Labels: Type: Feature

#524 feat: When ClientOptions.SendDefaultPii is false, send http headers without sensitive data
  fasthttp/sentryfasthttp_test.go
  http/sentryhttp_test.go
  interfaces.go
  interfaces_test.go
Labels: Type: Bug

#528 doc: Prepare 0.17.0
  CHANGELOG.md
Labels: Type: Documentation

#530 ci: Add Codecov
  .github/workflows/test.yml
Labels: Status: In Progress, Type: Improvement

#540 feat: Add DSN getters
  CHANGELOG.md
  dsn.go
  dsn_test.go
Labels: Type: Feature

#541 docs: Fixed broken links
  README.md
Labels: Type: Documentation

#539 feat(tracing): Add Span.SetDynamicSamplingContext method
  CHANGELOG.md
  tracing.go
  tracing_test.go
Labels: Type: Feature

#542 feat: Add Span.SetData()
  CHANGELOG.md
  tracing.go
  tracing_test.go
Labels: Type: Feature

#543 feat: Add Span.IsTransaction()
  CHANGELOG.md
  tracing.go
  tracing_test.go
Labels: Type: Feature

#544 test: Run tests and collect coverage for all submodules, if present
  .github/workflows/test.yml
  .gitignore
  Makefile
Labels: Type: Improvement

#546 feat(tracing): Add a new SpanOption: SpanSampled
  CHANGELOG.md
  tracing.go
  tracing_test.go
Labels: Type: Feature

#545 feat(tracing): Add TraceParentContext and helper functions
  CHANGELOG.md
  tracing.go
  tracing_test.go
Labels: Type: Improvement

#548 fix(test): Run test with coverage for all packages in a module
  Makefile
Labels: Type: Improvement

#537 feat: Add initial OpenTelemetry support
  otel/context.go
  otel/event_processor.go
  otel/event_processor_test.go
  otel/go.mod
  otel/go.sum
  otel/helpers_test.go
  otel/internal/dummy/dummy.go
  otel/internal/utils/mapotelstatus.go
  otel/internal/utils/sentryrequest.go
  otel/internal/utils/spanattributes.go
  otel/propagator.go
  otel/propagator_test.go
  otel/span_map.go
  otel/span_processor.go
  otel/span_processor_test.go
Labels: Type: Feature, Topic: OpenTelemetry

#558 feat(tracing): Add a method to get transaction for given span
  CHANGELOG.md
  tracing.go
  tracing_test.go
Labels: Type: Feature
