Repository getsentry/sentry-go, pull requests merged in 2023-06, with the labels that each got.

#644 feat(gin): Add transactions to Gin integration
  gin/sentrygin.go
  gin/sentrygin_test.go
  tracing.go
Labels: Status: In Progress, Type: Improvement

#626 feat: Add initial profiling support
  CHANGELOG.md
  _examples/profiling/main.go
  client.go
  example_transportwithhooks_test.go
  interfaces.go
  internal/traceparser/README.md
  internal/traceparser/parser.go
  internal/traceparser/parser_test.go
  profile_sample.go
  profiler.go
  profiler_other.go
  profiler_test.go
  profiler_windows.go
  stacktrace.go
  stacktrace_test.go
  traces_profiler.go
  traces_profiler_test.go
  tracing.go
  transport.go
  transport_test.go
Labels: Status: In Progress, Type: Feature

#638 fix: Clone scope.Context in multiple places to avoid concurrent reads/writes
  _examples/basic/main.go
  _examples/recover-repanic/main.go
  scope.go
  scope_test.go
  tracing.go
  tracing_test.go
Labels: Status: In Progress

#654 doc: Prepare 0.22.0 release
  CHANGELOG.md
Labels: Type: Documentation
