Repository getsentry/sentry-go, pull requests merged in 2024-04, with the labels that each got.

#802 Use set for sensitiveHeaders
  interfaces.go
Labels: Type: Improvement

#803 minor improvements
  dsn.go
  interfaces.go
  internal/ratelimit/category.go
  sentry.go
  traces_profiler.go
  tracing.go
Labels: Type: Improvement

#805 Revert "ci: add the common Danger workflow (#799)"
  .craft.yml
  .github/workflows/danger.yml
  CHANGELOG.md
Labels: Type: Improvement

#689 fix: missing stack trace for parsing error in logrusentry
  CHANGELOG.md
  interfaces.go
  logrus/logrusentry.go
  logrus/logrusentry_test.go
Labels: Status: In Progress, Type: Improvement

#800 Move exception group fields to mechanism
  client_test.go
  interfaces.go
  interfaces_test.go
  logrus/logrusentry_test.go
  util.go
  util_test.go
Labels: Type: Feature

#807 Add transactions to fiber
  fasthttp/sentryfasthttp_test.go
  fiber/sentryfiber.go
  fiber/sentryfiber_test.go
  gin/sentrygin.go
Labels: Type: Feature

#806 Fix setting of tracing variables
  traces_profiler.go
  traces_profiler_test.go
Labels: Type: Improvement

#808 feat(negroni): performance tracing
  negroni/sentrynegroni.go
  negroni/sentrynegroni_test.go
Labels: Type: Feature

#809 feat(iris): performance tracing
  _examples/iris/main.go
  go.mod
  go.sum
  iris/example_test.go
  iris/sentryiris.go
  iris/sentryiris_test.go
Labels: Type: Feature

#775 Add`FailureIssueThreshold` & `RecoveryThreshold` to MonitorConfig
  check_in.go
  client_test.go
Labels: Type: Improvement

#789 feat(metrics): add basic metrics type support
  interfaces.go
  interfaces_test.go
  metrics.go
  metrics_test.go
  transport.go
  transport_test.go
Labels: Type: Feature
