Repository getsentry/sentry-go, pull requests merged in 2024-09, with the labels that each got.

#877 Function grouping prefix fix
  CHANGELOG.md
  stacktrace.go
  stacktrace_below_go1.21.go
  stacktrace_below_go1.21_test.go
  stacktrace_go1.21.go
  stacktrace_go1.21_test.go
Labels: Type: Improvement

#871 Implement hijacker interface for Negroni integration
  CHANGELOG.md
  http/sentryhttp.go
  negroni/sentrynegroni.go
  wrap_writer.go
  wrap_writer_test.go
Labels: Type: Breaking, Type: Bug

#875 fix(http): use route name from 'r.Pattern' instead
  CHANGELOG.md
  http/sentryhttp.go
  internal/traceutils/route_name_below_go1.23.go
  internal/traceutils/route_name_below_go1.23_test.go
  internal/traceutils/route_name_go1.23.go
  internal/traceutils/route_name_go1.23_test.go
  negroni/sentrynegroni.go
Labels: Type: Improvement

#862 Tracing without performance improvements
  dynamic_sampling_context.go
  echo/sentryecho.go
  fasthttp/sentryfasthttp.go
  fiber/sentryfiber.go
  gin/sentrygin.go
  http/sentryhttp.go
  hub.go
  hub_test.go
  iris/sentryiris.go
  negroni/sentrynegroni.go
  scope.go
  tracing.go
  tracing_test.go
Labels: Type: Improvement

#882 Revert "Add ability to skip frames (#852)"
  client.go
  stacktrace.go
  stacktrace_test.go
Labels: Type: Improvement

#883 Prepare 0.29.0
  CHANGELOG.md
Labels: Type: Documentation
