Repository getsentry/sentry-go, pull requests merged in 2024-12, with the labels that each got.

#913 Add slog and zerolog guides to readme
  README.md
Labels: Type: Documentation

#915 Remove support for Profiling
  _examples/profiling/main.go
  client.go
  interfaces.go
  internal/traceparser/README.md
  internal/traceparser/parser.go
  internal/traceparser/parser_test.go
  profile_sample.go
  profiler.go
  profiler_other.go
  profiler_test.go
  profiler_windows.go
  traces_profiler.go
  traces_profiler_test.go
  tracing.go
  transport.go
  transport_test.go
Labels: Type: Breaking

#918 Update README.md
  README.md
Labels: Type: Documentation

#925 chore(dependabot): Change interval to monthly
  .github/dependabot.yml
Labels: Type: Improvement

#894 addworker notification for preventing goroutines leak
  CHANGELOG.md
  client.go
  go.mod
  go.sum
  mocks_test.go
  otel/go.sum
  otel/helpers_test.go
  slog/go.sum
  transport.go
  transport_test.go
  zerolog/go.sum
Labels: Type: Improvement

#939 Fix typos / add comments for integrations
  echo/sentryecho.go
  fasthttp/sentryfasthttp.go
  fiber/sentryfiber.go
  gin/sentrygin.go
  http/sentryhttp.go
  iris/sentryiris.go
  logrus/logrusentry.go
  negroni/sentrynegroni.go
Labels: Type: Documentation

#942 Revert “Create modules for integrations (#919)”
  .craft.yml
  CHANGELOG.md
  _examples/iris/main.go
  echo/go.mod
  echo/go.sum
  fasthttp/go.mod
  fasthttp/go.sum
  fiber/go.mod
  fiber/go.sum
  gin/go.mod
  gin/go.sum
  go.mod
  go.sum
  iris/go.mod
  iris/go.sum
  iris/sentryiris.go
  logrus/go.mod
  logrus/go.sum
  negroni/go.mod
  negroni/go.sum
  otel/go.mod
  slog/go.mod
  slog/go.sum
  zerolog/go.mod
  zerolog/go.sum
Labels: Type: Bug
