Repository getsentry/sentry-go, pull requests merged in 2025-05, with the labels that each got.

#988 chore(deps): update github.com/stretchr/testify to v1.8.4
  go.mod
  go.sum
Labels: Improvement

#1007 Add attributes API
  attribute/builder_test.go
  attribute/bulider.go
  attribute/rawhelpers.go
  attribute/value.go
  attribute/value_test.go
Labels: Go, Feature

#1002 fix(otel): Prefer http route over http target for span description
  otel/go.mod
  otel/go.sum
  otel/internal/utils/mapotelstatus_test.go
  otel/internal/utils/spanattributes.go
  otel/internal/utils/spanattributes_test.go
Labels: Improvement

#1013 Do not push a new scope on `StartSpan`
  scope.go
  scope_test.go
  tracing.go
Labels: Bug

#1010 Add initial logger implementation
  .codecov.yml
  _examples/logs/main.go
  batch_logger.go
  client.go
  interfaces.go
  log.go
  log_fallback.go
  log_test.go
  transport.go
  transport_test.go
Labels: Feature
