Repository getsentry/sentry-go, pull requests merged in 2025-06, with the labels that each got.

#1034 fix: use correct Level signature for logs
  interfaces.go
  log.go
Labels: Improvement

#1038 Fix remove sentry.origin for sentry logger
  log.go
  log_test.go
Labels: Improvement

#935 Implement flush with context
  _examples/flush-with-context/main.go
  client.go
  hub.go
  hub_test.go
  log_test.go
  logrus/README.md
  logrus/logrusentry.go
  mocks.go
  sentry.go
  slog/README.MD
  transport.go
  transport_test.go
  zerolog/README.md
Labels: Feature

#1036 Add logrus logs integration
  _examples/logrus/main.go
  logrus/README.md
  logrus/go.mod
  logrus/go.sum
  logrus/logrusentry.go
  logrus/logrusentry_test.go
Labels: Feature

#1033 Add slog logs integration
  _examples/slog/main.go
  slog/README.MD
  slog/converter.go
  slog/sentryslog.go
  slog/sentryslog_test.go
Labels: Feature

#1041 Remove handling for specific logrus keys
  logrus/logrusentry.go
  logrus/logrusentry_test.go
Labels: Bug
