Repository getsentry/sentry-go, pull requests merged in 2025-01, with the labels that each got.

#946 Bump Gin to version 1.9.1
  gin/go.mod
  gin/go.sum
Labels: Type: Improvement

#947 Bump golang.org/x/net to 0.33.0
  echo/go.mod
  echo/go.sum
  gin/go.mod
  gin/go.sum
  iris/go.mod
  iris/go.sum
Labels: Type: Improvement

#936 Add HubProvider functionality for logrus integration
  CHANGELOG.md
  logrus/logrusentry.go
  logrus/logrusentry_test.go
Labels: Type: Feature

#950 Rename sentry-go/logrus module
  logrus/go.mod
Labels: Type: Bug

#951 Prepare 0.31.1
  CHANGELOG.md
Labels: Type: Documentation

#952 add hubProvider details to readme in logrus
  logrus/README.md
Labels: Type: Documentation

#957 handle sentry.Request properly in sentrylogrus
  logrus/logrusentry.go
  logrus/logrusentry_test.go
Labels: Type: Improvement
